[requirements]
paths = ['requirements/**/*.md']

[satisfy]
rules = [
    # Functional requirements are satisfied when there is implementation
    # under source directory and a test under tests.
    ['FR-.*', ['(?i)^nerm/.* .*Implement', '^tests/']],

    # Documentation requirements are satisfied when they have been mentioned
    # in e.g. commit message.
    ['DR-.*', '.*'],
]

[formats.gitref]
prefix = '- &#9939; '
format = '[{c.shorthash}](https://github.com/PetteriAimonen/nerm/commit/{c.fullhash}): {c.fulltext}'

[formats.gitadd]
prefix = '- &#9733; Added by '
format = '{c.author} in [{c.shorthash}](https://github.com/PetteriAimonen/nerm/commit/{c.fullhash}) on {c.date}'